version: 0.0.{build}-{branch}
image: Visual Studio 2017
configuration: Release
build_script:
- ps: ./Build $env:APPVEYOR_BUILD_NUMBER $env:APPVEYOR_REPO_BRANCH
artifacts:
- path: '**/*.nuspec'
  name: nuspecs
- path: src/**/*.nupkg
  name: nupkgs
  deploy:
- provider: NuGet
  api_key:
    secure: yMAQaBjoeB2EANrW5ef9ycXf8mPVucIZFc8/bP+vAjJQs05RL8alt1N/DBELIcZs
  on:
    branch: master
- provider: NuGet
  api_key:
    secure: yMAQaBjoeB2EANrW5ef9ycXf8mPVucIZFc8/bP+vAjJQs05RL8alt1N/DBELIcZs
  on:
    branch: dev